apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: production
spec:
  kind: Permanent
  label: Production
  namespace: jenkinsx-meetup-prod
  order: 200
  previewGitInfo:
    user: {}
  promotionStrategy: Manual
  source:
    ref: master
    url: https://github.com/ThmX/jenkinsx-meetup-prod.git
  teamSettings:
    defaultScheduler:
      kind: ""
      name: ""
status: {}
